In [75]:
import numpy as np

## Basics


In [76]:
arra_1=np.array([12,4,2,34])
print(arra_1)

[12  4  2 34]


In [77]:
arra_2=np.array([[12.4,12.3,1.33],[1,9.6,3.4]])
print(arra_2)

[[12.4  12.3   1.33]
 [ 1.    9.6   3.4 ]]


In [78]:
# Get Dimensions
arra_1.ndim

1

In [79]:
#shape
arra_2.shape

(2, 3)

In [80]:
#size
arra_1.dtype

dtype('int32')

## Getting Specific elements,rows and columns

In [81]:
arra_3=np.array([[12,45,22,56,2,45,8],[19,34,11,44,23,1,0]])
print(arra_3)

[[12 45 22 56  2 45  8]
 [19 34 11 44 23  1  0]]


In [82]:
arra_3[1,3]

44

In [83]:
# sepicfic row
arra_3[0,:]

array([12, 45, 22, 56,  2, 45,  8])

In [84]:
arra_3[0,:-1]

array([12, 45, 22, 56,  2, 45])

In [85]:
arra_3[1,:3]

array([19, 34, 11])

In [86]:
#Specific column
arra_3[:,2]

array([22, 11])

In [87]:
arra_3[:,-1]

array([8, 0])

In [88]:
arra_3[1,2:-1:1]

array([11, 44, 23,  1])

In [89]:
arra_3[0,0]=0
print(arra_3)

arra_3[0,-1]=12
print(arra_3)

[[ 0 45 22 56  2 45  8]
 [19 34 11 44 23  1  0]]
[[ 0 45 22 56  2 45 12]
 [19 34 11 44 23  1  0]]


## Different Types OF Arrays

In [90]:
# all zeros matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
# other number
np.full((4,2),23,dtype="float32")

array([[23., 23.],
       [23., 23.],
       [23., 23.],
       [23., 23.]], dtype=float32)

In [92]:
np.full_like(arra_2,0)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
#random decimal numbers
np.random.rand(2,3)

array([[0.79730412, 0.71620755, 0.25335868],
       [0.45436011, 0.34254434, 0.50949611]])

In [94]:
#random int number
np.random.randint(3,size=(3,3))

array([[1, 0, 1],
       [2, 0, 1],
       [2, 2, 0]])

In [95]:
#identity matrix
np.identity(2,dtype='int32')

array([[1, 0],
       [0, 1]])

In [96]:
#repeat any array
arra_4=np.array([[12,3,3]])
r1=np.repeat(arra_4,3,axis=0)
print(r1)

[[12  3  3]
 [12  3  3]
 [12  3  3]]


In [97]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
# Be careful when copying array
arra_5=np.array([12,3,6])
arra_6=arra_5
arra_6[0]=2
print(arra_5)

#copy function
arra_5=np.array([12,3,6])
arra_6=arra_5.copy()
arra_6[0]=2
print(arra_5)

[2 3 6]
[12  3  6]


## Mathematics

In [103]:
arra_7=np.array([1,2,3,4])
print(arra_7)

[1 2 3 4]


In [106]:
print(arra_7*8)
print(arra_7+3)
print(arra_7-2)
print(arra_7/2)

[ 8 16 24 32]
[4 5 6 7]
[-1  0  1  2]
[0.5 1.  1.5 2. ]


In [107]:
arra_8=np.array([0,1,0,1])
arra_7+arra_8

array([1, 3, 3, 5])

In [108]:
np.sin(12)

-0.5365729180004349

In [109]:
np.cos(0)

1.0

## Linear Algebra

In [114]:
arra_9=np.ones((2,3))
print(arra_9)

arra_10=np.full((3,2),2)
print(arra_10)

#multiply the matrix
np.matmul(arra_9,arra_10)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [116]:
#Find determinant
arra_11=np.identity(3)
np.linalg.det(arra_11)

1.0

In [119]:
arra_12=np.array([[12,45,22,56,2,45,8],[19,34,11,44,23,1,0]])
np.min(arra_12),np.max(arra_12),np.sum(arra_12)

(0, 56, 322)

# Reorgnizing the Array

In [129]:
before=np.array([[12,45,22,56,2,45,8],[19,34,11,44,23,1,0]])
print(before)
after=before.reshape((7,2))
print(after)

[[12 45 22 56  2 45  8]
 [19 34 11 44 23  1  0]]
[[12 45]
 [22 56]
 [ 2 45]
 [ 8 19]
 [34 11]
 [44 23]
 [ 1  0]]


## vertically stacking vectors

In [131]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [132]:
# Horizontal Stack
h1=np.zeros((2,4))
h2=np.ones((2,4))

np.hstack((h1,h2))


array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

# Miscellaneous

In [133]:
# Load Data From File

In [138]:
file_data= np.genfromtxt('data.txt',delimiter=",")
file_data=file_data.astype('int32')
file_data

array([[ 12,   3,   4,  55,   2, 432, 454,  55,  22,   5,  66],
       [ 33,   5,  73,  95,   0, 542,   2,  22,  44, 222,  45],
       [ 12,  44,  56,  78,  99,  76,  44,  12,  22,  33,   1]])

# Boolean and Advanced Indexing

In [139]:
file_data >33

array([[False, False, False,  True, False,  True,  True,  True, False,
        False,  True],
       [False, False,  True,  True, False,  True, False, False,  True,
         True,  True],
       [False,  True,  True,  True,  True,  True,  True, False, False,
        False, False]])

In [140]:
file_data[file_data >33]

array([ 55, 432, 454,  55,  66,  73,  95, 542,  44, 222,  45,  44,  56,
        78,  99,  76,  44])

In [144]:
np.any(file_data >33, axis=0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])